eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: employee-producer